### ISSUE TITLE
Can NextSV take gzipped input?

### ISSUE THREAD

**Issue by gbdias** [Nextomics/nextsv#10]
Hi,

Can NextSV take gzipped fasta files as input?

Thanks,
Guilherme

**Comment by fangli80** [comment]
Hi Guilherme, 
Thank you for using NextSV! 
Currently, NextSV does not support gzipped fasta files as input because blasr does not support it. Please manually unzip the file. We will support gzipped fasta files soon. 

Best, 
Li
