### ISSUE TITLE
Update with new aligners and SV callers?

### ISSUE THREAD

**Issue by gbdias** [Nextomics/nextsv#11]
Hi,

Thanks for developing NextSV!

Since alignment is the most CPU consuming part of all SV pipelines, adding an aligner such as Minimap2 seems like a good upgrade for your pipeline. Minimap2 is blazing fast!
Also, some new SV callers seem to be relatively fast and would make NextSV even more useful. These take an input file in bam format, so NextSV could actually use the same alignment for all of them.
- NanoSV https://github.com/mroosmalen/nanosv
- pbsv https://github.com/PacificBiosciences/pbsv
- Picky https://github.com/TheJacksonLaboratory/Picky/wiki

**Comment by fangli80** [comment]
Hi, 
Thank you for your suggestions! We will add the new aligners and SV callers soon! 

Best, 
Li
