### ISSUE TITLE
error in build.sh?

### ISSUE THREAD

**Issue by JhinAir** [Nextomics/nextsv#19]
Hi,
The 'sh build.sh' in build.sh should be replaced by 'make'.
Jing

**Comment by fangli80** [comment]
What error did you get? 
I changed build.sh to Makefile and you can use `make` to build the binaries. But the old `sh build.sh` should work fine too.

**Comment by fangli80** [comment]
Is this solved? Do you still have error with the new version? 

Thanks,
Li

**Comment by JhinAir** [comment]
in previous version, the 'sh build.sh' in build.sh should be replaced by 'make'. Then I can instill. It's solved anyway.

**Comment by fangli80** [comment]
Ok. Thanks for letting me know.
