### ISSUE TITLE
language suffix on user-facing program: nextsv.pl vs nextsv

### ISSUE THREAD

**Issue by 0xaf1f** [Nextomics/nextsv#2]
For this user-facing script, it's generally better not to expose implementation details like the language used to write the program. See <https://wiki.debian.org/UpstreamGuide#Language_extensions_in_scripts> for more details.

You already have nextsv.pl marked executable and a proper shebang line, so there is no need to keep the `.pl` suffix. In line with this, the documentation should probably be updated to instruct usage as `./nextsv` or to put the folder on the `PATH` and call it as simply `nextsv`.

**Comment by fangli80** [comment]
Thank you for your suggestion. We will modify this in the next release.
