### ISSUE TITLE
The number of SV output is very small

### ISSUE THREAD

**Issue by evayfang2019** [Nextomics/nextsv#21]
The default parameters were used and the maximum output was no more than 200 SVs. However, when I ran minimap2+cuteSV, more than 10 000 SVs were found.

**Comment by fangli80** [comment]
Hello, 
Could you please provide your command to run nextsv, and also check the size of the bam files in the nextsv output folder? 
NextSV runs cuteSV directly and did not modify the output 
By the way, do you mean that you ran minimap2 + cuteSV manually and you can get 10k SVs? 
Thanks, 
Li

**Comment by evayfang2019** [comment]
Hello, Dr, Li. Thanks for reply！

command to run nextsv:
`nextsv3 -a minimap2+winnowmap+ngmlr -i ./02.ccsbam2fq/1_A01 -o ./03.nextsv3/1_A01 -s m64057_210730_104906 -r ./hg38.fa -t 32 -p hifi -e base`
`sh ./03.nextsv3/1_A01/work.sh > ./03.nextsv3/1_A01/nextsv3_A01.log 2>&1 &`
nextsv3 input file: xxx.fq.fastq.gz  20.55GB; (.ccs.bam -> .fastq.gz by bam2fastq)
nextsv3 output .bam:   xxx.minimap2.sorted.bam  382.23MB;
nextsv3 output .vcf: 86kB (only 35 SVs).

Yes, I ran minimap2 + cuteSV manually and  get 10k SVs.

Thanks,
Fang

**Comment by fangli80** [comment]
Sorry for the late reply. I was traveling last week. The size of the bam file is much smaller than the fastq.gz file, which means there might be error in mapping or the reads cleaning step. Could you please also check the size of the fastq.gz file? 

Thanks, 
Li

**Comment by fangli80** [comment]
I realized that this is a bug of longreadqc (which is included in NextSV) and it only affected PacBio HiFi reads. 

It is fixed in the latest version.
