### ISSUE TITLE
licensing clarification

### ISSUE THREAD

**Issue by 0xaf1f** [Nextomics/nextsv#3]
I'd like to package this for Debian's non-free section (not part of Debian proper) because of the commercial use restriction, but I have to clarify a few points regarding your licensing and whether you would allow it.

Do you allow redistribution? Do you allow modification and redistribution of modified versions? Please clarify these points in the README.

Many thanks for your consideration (and apologies for the barrage of issues)

**Comment by fangli80** [comment]
We have added this in README file.
