### ISSUE TITLE
Support for NGM-LR

### ISSUE THREAD

**Issue by eldariont** [Nextomics/nextsv#4]
Hi,

the author of Sniffles recommends using NGM-LR for mapping rather than BWA-MEM. Do you know how Sniffles compares against PBHoney when using NGM-LR? And, do you plan to support NGM-LR in the future?

Cheers
David

**Comment by fangli80** [comment]
Yes. I plan to support NGM-LR in the future? Thank you.

**Comment by fangli80** [comment]
NextSV now supports NGM-LR. Thanks.
