### ISSUE TITLE
input file

### ISSUE THREAD

**Issue by RuiMMFaria** [Nextomics/nextsv#5]
Hi,

just edited my previous post, as I misunderstood something. Here is the new question:

If I understood correctly we have to provide an input file with the name of all fastq files we will map (and their path). In your example, does each line of the example.fastq.fofn correspond to a different run? or does each file respresent something else?

I just have a single file (fastq format) with the subreads from a single run. So, should I provide a single line in the example.fastq.fofn or do I have to first group the reads somehow?

Thanks a lot.
Rui

**Comment by fangli80** [comment]
Hi, 
Sorry for the late reply. 
Each line of the example.fastq.fofn correspond to a different run for alignment. After all fastq files finished, there is a merge and call shell script to merge all the bam files and call the variants. 

If you have a single file, you can just provide a single line in the fastq.fofn file.
