### ISSUE TITLE
error [bwt_restore_sa] SA-BWT inconsistency: primary is not the same while running nextsv

### ISSUE THREAD

**Issue by RatneshSingh** [Nextomics/nextsv#7]
I received an error for [bwt_restore_sa] SA-BWT inconsistency: primary is not the same while running nextsv.

it is caused by bwa index and sawriter both creating index file with same name and overwriting each other. and then complaining about .sa file not being  correct.

to solve the issue, create sawriter and bwa indexes in two different folders and provide the path in the config file.

**Comment by fangli80** [comment]
Thank you for your comment. We also noticed this issue.  As described in the README file, there are two parameters for reference FASTA file in the config file.  The `ref_fasta`  is the path to reference genome FASTA file used by BWA and NGMLR. The `ref_blasr` is the path to reference genome FASTA file used by BLASR.  This two files should be in different folders. (You can link one file to another folder)
